'use strict';

let sampleWhite = [
  'Jacob giving a thumbs up',
  'A craps table',
  'Accidentally working on main',
  'My teammates',
  'Middleware',
  'Merge Conflicts',
  'Andrew asking a question',
  'My mental health',
  'Cynar\'s butt',
  'Gituations',
  'Submitting an empty repo',
  'Ryan\'s birds',
  '18 cups of coffee',
  'Imposter Syndrome',
  'The crying corner',
  'Reading the docs',
  'Neglecting your family and friends',
  'JB\'s shirts',
  'Dozing off with your camera on',
  'Forgetting your learning journal',
  'A missing semicolon',
  'Salmon Cookies',
  'Getting COVID',
  'Waking up at 8:59',
  'A power outage',
  'Pulling an all-nighter',
  'Not remembering the last time you left the house',
  'Joining the zoom with no shirt and hoping nobody noticed',
  'Getting called on during a bathroom break',
  'Broken links',
  'Having 27 tabs open',
  'Infinite loops',
  'Jest',
  'A good TA',
  'The 15 minute rule',
  'Roger Huba driving the Millennium Falcon',
  'Finishing with an 89',
  'Filling out the README',
  'npm i',
  'Being charged $1,000 by AWS',
  'Talking while muted',
  'Pull requests',
  'Finding out you weren\'t muted',
  'Turning it off and then on again',
  'Moving across the country in the middle of school',
  'A pay wall',
  'A windows computer',
  'Maximum tears per hour',
  'The longest 6 months of my life',
  'Jeff Bezos',
  'Really great facial hair',
  'Error Codes',
  'A justified god complex',
  'Crippling depression',
  'Eating a lemon like an apple just to feel something again',
  'Vinicio',
  'Unending suffering'
];

let sampleBlack = [
  'JavaScript 401 is like living in Spain without _____.',
  'The easiest part of software development is _____.',
  'What has been making life difficult at Code Fellows?',
  'The partner power hour this Friday will focus on _____.',
  'When I graduate Code Fellows,Im going to make an app for_____.',
  'A successful whiteboard interview begins with a firm handshake, and ends with _____.',
  'Software development feels like _____.',
  'The Docs say to try _____.',
  'Did _____ fix the bug?',
  'I got docked points on the last lab for ____.',
  'As a developer, my greatest achievement is _____.',
  'I didnt become a developer for the money, I did it for _____.'
];

module.exports = {
  sampleWhite,
  sampleBlack
};
